spring:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/classicmodels
        username: root
        password: root
    jpa:
        show-sql: true
        hibernate:
            naming:
                physical-strategy: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher